FROM condaforge/mambaforge:latest
RUN mamba install -q -y -c conda-forge openbabel
COPY requirements.txt .
RUN pip install torch=2.0.0 ase numpy pysisyphus
WORKDIR /app
COPY calculators/ calculators/
COPY models/ models/
ENTRYPOINT [ "python3" ,"/app/calculators/"]